### ISSUE TITLE
Image is missing

### ISSUE THREAD

**Issue by dannykopping** [DevOpsHiveHQ/kustomize-plugin-merger#77]
Thanks for this plugin, it's exactly what I needed!

The container image seems to be missing, though:

```bash
$ docker run ghcr.io/devopshivehq/kustomize-generator-merger -v
Unable to find image 'ghcr.io/devopshivehq/kustomize-generator-merger:latest' locally
docker: Error response from daemon: denied.
See 'docker run --help'.
```

I have a token issued which should authenticate me to download the image.

And https://github.com/orgs/DevOpsHiveHQ/packages?repo_name=kustomize-plugin-merger shows no images.

I got it working by compiling the image and `exec`-ing locally, but this is not ideal for CI environments.

**Comment by aabouzaid** [comment]
Hi @dannykopping :wave: 
Yeah, I think the image was not moved when I moved the project to DevOpsHive org.

I will check if I can repush it or rebuild it again.

**Comment by aabouzaid** [comment]
@dannykopping the package repo was private when moved. I made it public, so it should work now 🙌

**Comment by aabouzaid** [comment]
@dannykopping Great to hear that! :tada: 
It would be great if you open an issue or rather a feature request to add other archs for Docker image. Right now only amd64 is created for Docker.

**Comment by aabouzaid** [comment]
@dannykopping, we have a Docker image that supports both AMD and ARM now.
Would you like to test it?
```
docker pull ghcr.io/devopshivehq/kustomize-generator-merger:2.1.0
```
